import { defineConfig, HeadConfig, type DefaultTheme } from 'vitepress';
// The typedoc-sidebar.json files are generated by docs:api and may not exist
// yet when lint builds this program, so type them explicitly.
import typedocSidebarItemsJson from '../api/reference/typedoc-sidebar.json';
import mobxSidebarItemsJson from '../api/lit-ui-router-mobx/typedoc-sidebar.json';
import navigationSidebarItemsJson from '../api/navigation-location-plugin/typedoc-sidebar.json';

const typedocSidebarItems =
  typedocSidebarItemsJson as DefaultTheme.SidebarItem[];
// The companion references carry their kind categories (Classes, Interfaces,
// …) collapsed, mirroring how the flagship reference groups members — each
// category heading links to its generated kind-index page.
const mobxSidebarItems = mobxSidebarItemsJson as DefaultTheme.SidebarItem[];
const navigationSidebarItems =
  navigationSidebarItemsJson as DefaultTheme.SidebarItem[];

const baseUrl = 'https://lit-ui-router.dev';

function makeSidebar() {
  return [
    {
      text: 'Introduction',
      items: [{ text: 'What is Lit UI Router?', link: '/introduction' }],
    },
    {
      text: 'Tutorial',
      items: [
        { text: 'Hello World', link: '/tutorial/helloworld' },
        { text: 'Hello Solar System', link: '/tutorial/hellosolarsystem' },
        { text: 'Hello Galaxy', link: '/tutorial/hellogalaxy' },
        { text: 'Live Examples', link: '/tutorial/live-examples' },
      ],
    },
    {
      text: 'Guides',
      items: [
        { text: 'Overview', link: '/guides/' },
        { text: 'Location Plugins', link: '/guides/location-plugins' },
        { text: 'Unmatched URLs (404)', link: '/guides/unmatched-urls' },
        {
          text: 'Server-Side Routing',
          link: '/guides/server-route-matching',
        },
        { text: 'Route Guards', link: '/guides/route-guards' },
        {
          text: 'Component Lifecycle Hooks',
          link: '/guides/component-lifecycle',
        },
        { text: 'Reactive Components', link: '/guides/reactive-components' },
      ],
    },
    {
      text: 'Companion Packages',
      items: [
        { text: 'Overview', link: '/packages/' },
        {
          text: 'MobX',
          collapsed: true,
          items: [
            { text: 'lit-ui-router-mobx', link: '/packages/mobx' },
            {
              text: 'API',
              link: '/api/lit-ui-router-mobx/',
              collapsed: false,
              items: mobxSidebarItems,
            },
          ],
        },
        {
          text: 'Navigation Location',
          collapsed: true,
          items: [
            {
              text: 'ui-router-navigation-location-plugin',
              link: '/packages/navigation-plugin',
            },
            {
              text: 'API',
              link: '/api/navigation-location-plugin/',
              collapsed: false,
              items: navigationSidebarItems,
            },
          ],
        },
      ],
    },
    {
      text: 'Sample App',
      items: [
        { text: 'Overview', link: '/sample-app' },
        { text: 'Vanilla', link: '/app', target: '_self' },
        { text: 'MobX', link: '/app-mobx', target: '_self' },
        { text: 'Hash', link: '/app-hash', target: '_self' },
      ],
    },
    {
      text: 'API',
      items: [
        { text: 'Overview', link: '/api/' },
        {
          text: 'lit-ui-router',
          link: '/api/reference/',
          collapsed: true,
          items: typedocSidebarItems,
        },
      ],
    },
  ];
}

const GOOGLE_ANALYTICS_TRACKING_ID =
  process.env.VITE_GOOGLE_ANALYTICS_TRACKING_ID;

if (!GOOGLE_ANALYTICS_TRACKING_ID) {
  console.warn('GOOGLE_ANALYTICS_TRACKING_ID missing');
} else {
  console.info(`GOOGLE_ANALYTICS_TRACKING_ID=${GOOGLE_ANALYTICS_TRACKING_ID}`);
}

const config = {
  outDir: 'dist',
  title: 'Lit UI Router',
  description: 'A @uirouter implementation for Lit',
  cleanUrls: true,
  ignoreDeadLinks: ['/app', '/app-mobx', /^\/examples\//],
  // ignoreDeadLinks: true,
  vite: {
    configFile: './.vitepress/vite.config.ts',
  },
  vue: {
    template: {
      compilerOptions: {
        isCustomElement(tag: string) {
          return tag.startsWith('sp-');
        },
      },
    },
  },
  themeConfig: {
    logo: '/images/lit-ui-router.svg',
    nav: [
      { text: 'Home', link: '/' },
      {
        text: 'Docs',
        items: [
          { text: 'Introduction', link: '/introduction' },
          { text: 'Tutorial', link: '/tutorial/helloworld' },
          { text: 'Guides', link: '/guides/' },
          { text: 'Companion Packages', link: '/packages/' },
          { text: 'API', link: '/api/' },
        ],
      },
      {
        text: 'Sample App',
        items: [
          { text: 'Overview', link: '/sample-app' },
          { text: 'Vanilla', link: '/app', target: '_self' },
          { text: 'MobX', link: '/app-mobx', target: '_self' },
          { text: 'Hash', link: '/app-hash', target: '_self' },
        ],
      },
    ],
    sidebar: makeSidebar(),
    socialLinks: [
      { icon: 'github', link: 'https://github.com/simshanith/lit-ui-router' },
    ],
  },
  head: [
    [
      'script',
      {
        async: '',
        src: `https://www.googletagmanager.com/gtag/js?id=${GOOGLE_ANALYTICS_TRACKING_ID}`,
      },
    ],
    [
      'script',
      {},
      `window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', '${GOOGLE_ANALYTICS_TRACKING_ID}');`,
    ],
  ] satisfies HeadConfig[],
};

export default defineConfig({
  ...config,
  transformHead({ pageData }) {
    const head: HeadConfig[] = [];
    const imageUrl = `${baseUrl}/images/lit-ui-router.png`;
    const imageAlt = 'Lit UI Router logo';
    const twitterCreator = '@simloovoo';
    const twitterCard = 'summary_large_image';
    const ogType = 'website';

    let title: string;
    let description: string;
    let pageUrl: string;

    if (pageData.relativePath === 'index.md') {
      title = config.title;
      description = config.description;
      pageUrl = baseUrl;
    } else {
      // frontmatter is Record<string, any>.
      title =
        (pageData.frontmatter.title as string | undefined) || pageData.title;
      title = title ? `${config.title} - ${title}` : config.title;

      description =
        (pageData.frontmatter.description as string | undefined) ||
        pageData.description ||
        config.description;

      const pagePath = pageData.relativePath
        .replace(/^\.\//, '')
        .replace(/\/index\.md$/, '/')
        .replace(/\.md$/, '');
      pageUrl = `${baseUrl}/${pagePath}`;
    }

    head.push(
      ['meta', { property: 'og:title', content: title }],
      ['meta', { property: 'og:description', content: description }],
      ['meta', { property: 'og:image', content: imageUrl }],
      ['meta', { property: 'og:image:alt', content: imageAlt }],
      ['meta', { property: 'og:url', content: pageUrl }],
      ['meta', { property: 'og:type', content: ogType }],
      ['meta', { property: 'og:site_name', content: config.title }],
      ['meta', { name: 'twitter:card', content: twitterCard }],
      ['meta', { name: 'twitter:creator', content: twitterCreator }],
      ['meta', { name: 'twitter:title', content: title }],
      ['meta', { name: 'twitter:description', content: description }],
      ['meta', { name: 'twitter:image', content: imageUrl }],
      ['meta', { name: 'twitter:image:alt', content: imageAlt }],
    );
    return head;
  },
});
